# ข้อสอบปลายภาควิชาการประมวลผลข้อมูลขนาดใหญ่

# นาย ไพสิน ชิณวงศ์ 6212732105

## 1. จงสร้าง ndarray ดังนี้

In [ ]:
'''
array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)
'''

In [12]:
# เขียนคำตอบลงในเชลนี้

import numpy as np


A = np.array([[4.   , 3.285, 3.5  , 4.],[3.2  , 3.8  , 4.   , 4.],[3.96 , 3.92 , 4.   , 4.]],np.float16)
A



array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

## 2. จงแสดงจำนวน แถว และ คอลัมน์ ของ array ที่สร้างขึ้นจากข้อ 1.

In [13]:
# เขียนคำตอบลงในเชลนี้
A.shape


(3, 4)

## 3. จงสร้าง array ดังต่อไปนี้

In [ ]:
'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
'''

In [11]:
# เขียนคำตอบลงในเชลนี้

B = np.array([[1 , 2 , 3 , 4],[5,  6,  7 , 8],[9 ,10 ,11, 12]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 4. จากข้อที่ 3 จงแสดงข้อมูลดังต่อไปนี้

In [ ]:
'''
[5 6 7 8]
'''

In [14]:
# เขียนคำตอบลงในเชลนี้
print(B[1,:])


[5 6 7 8]


## 5. จากข้อที่ 3. จงแสดงข้อมูลดังต่อไปนี้

In [ ]:
'''
array([12, 11, 10])
'''

In [17]:
# เขียนคำตอบลงในเชลนี้
lt = B[2, 1:]
lt[::-1]

array([12, 11, 10])

## 6. จงเขียนโปรแกรมที่ทำการเขียนข้อมูลต่อไปนี้ลงในไฟล์ ชื่อ file.txt

In [ ]:
'''
This is 1st line
This is 2nd line
This is 3rd line
This is 4th line
This is 5th line
'''

In [1]:
# เขียนคำตอบลงในเชลนี้
import csv
data = ["This is 1st line",
        "This is 2nd line",
        "This is 3rd line",
        "This is 4th line",
        "This is 5th line"]

with open('D:/programming64/basic_python/Bigdata/Homeworke/HW_003/finaltest/file.txt', 'w') as fp:
    for line in data:
        fp.write(line+"\n")
        
with open('D:/programming64/basic_python/Bigdata/Homeworke/HW_003/finaltest/file.txt', 'r') as fp:  
    line = fp.readline()
    while line:
        print("{}".format(line.strip()))
        line = fp.readline()


This is 1st line
This is 2nd line
This is 3rd line
This is 4th line
This is 5th line


## 7. จงเขียนข้อมูลต่อไปนี้ลงในไฟล์ในรูปแบบ CSV

In [ ]:
'''
myData = [
            ["first_name", "second_name", "Grade"],
            ['Alex', 'Brian', 'A'],
            ['Tom', 'Smith', 'B']
        ]
'''

In [2]:
# เขียนคำตอบลงในเชลนี้

myData = [
            ["first_name", "second_name", "Grade"],
            ['Alex', 'Brian', 'A'],
            ['Tom', 'Smith', 'B']
        ]

with open('D:/programming64/basic_python/Bigdata/Homeworke/HW_003/finaltest/myData.csv','w') as newfile :
    write = csv.writer(newfile)
    write.writerows(myData)

print("complete")


complete


## 8.จงนำข้อมูลต่อไปนี้ไปสร้างเป็น Data Frame

In [ ]:
'''
persons = {
    "ชื่อ": ["พิศาล", "ปรเมษฐ", "สมชาย"],
    "สกุล": ["สุขขี", "สุขะตะ", "รักดี"],
    "โทร": ["0842982456", "0889152456", "0886123546"]
}
'''

In [1]:
# เขียนคำตอบลงในเชลนี้
import pandas as pd
persons = {
    "ชื่อ": ["พิศาล", "ปรเมษฐ", "สมชาย"],
    "สกุล": ["สุขขี", "สุขะตะ", "รักดี"],
    "โทร": ["0842982456", "0889152456", "0886123546"]
}
data = pd.DataFrame(persons)
data.head()

ชื่อ    สกุล         โทร
0   พิศาล   สุขขี  0842982456
1  ปรเมษฐ  สุขะตะ  0889152456
2   สมชาย   รักดี  0886123546

## 9. จาก Data Frame ในข้อที่ 8 จงแสดงเฉพาะคอลัม เบอร์โทรศัพท์

In [3]:
# เขียนคำตอบลงในเชลนี้

data[["โทร"]]

โทร
0  0842982456
1  0889152456
2  0886123546

## 10. จาก Data Frame ในข้อที่ 8 จงแสดงเฉพาะข้อมูลของ พิศาล

In [6]:
# เขียนคำตอบลงในเชลนี้

tel = data[data["ชื่อ"]=='พิศาล']
tel

ชื่อ   สกุล         โทร
0  พิศาล  สุขขี  0842982456